version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ddd-orders-app
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - laravel

  caddy:
    image: caddy:2-alpine
    container_name: ddd-orders-caddy
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - ./.docker/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: postgres:16-alpine
    container_name: ddd-orders-db
    environment:
      POSTGRES_DB: ddd_orders
      POSTGRES_USER: ddd_user
      POSTGRES_PASSWORD: ddd_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  postgres-data:
